name: Deploy TailTails App on VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.PROJECT_PATH }} && \
            # сброс локальных правок на сервере
            git reset --hard HEAD && \
            # свежий код
            git pull origin main && \
            # пересборка контейнера
            docker compose up -d --build && \
            # миграции
            docker compose exec -T fastapi_app alembic upgrade head && \
            # очистка от старых версий
            docker image prune -f
